[project]
name = "benchmarl-demir"
version = "0.1.0"
description = "Research project with DEMIR and CUDA 11.8 support"
requires-python = "==3.12.2"
dependencies = [
    "torch==2.5.1+cu118",
    "torchvision==0.20.1+cu118",
    "torchrl==0.6.0",
    "tensordict==0.6.0",
    "numpy<2.0.0",
    "faiss-cpu",
    "hydra-core",
    "tqdm",
    "wandb",
    "av<14",
    "moviepy",

    "unified-planning",
    "pettingzoo",
    "gymnasium",
    "minigrid",
    "pandas",
    "matplotlib",
    "seaborn",
    "hydra-core",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
