_wandb:
    value:
        cli_version: 0.25.0
        e:
            efdogzcnszkm952xt25djajl4zv2d52l:
                args:
                    - --variant
                    - r2d2_demir
                    - --env-id
                    - BabyAI-KeyCorridorS4R3-v0
                    - --seed
                    - "100"
                codePath: fine_tuned/minigrid/r2d2_run.py
                codePathLocal: fine_tuned/minigrid/r2d2_run.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "243298951168"
                email: kajetan.piotr.frackowiak@gmail.com
                executable: /home/kajetan/Documents/inzynierka_kod_zrodlowy/.venv/bin/python3
                git:
                    commit: 1c1c395d7a90fe2fbb0fe646400f6bba4638fcfb
                    remote: https://github.com/s28404/inzynierka_kod_zrodlowy.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-f010ab2c-9f8a-dfc2-d888-045d09377d67
                host: Kajetandell
                memory:
                    total: "16630743040"
                os: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/kajetan/Documents/inzynierka_kod_zrodlowy/fine_tuned/minigrid/r2d2_run.py
                python: CPython 3.12.2
                root: logs_thesis/minigrid
                startedAt: "2026-05-22T09:49:50.916832Z"
                writerId: efdogzcnszkm952xt25djajl4zv2d52l
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.2
            "5": 0.25.0
            "8":
                - 2
            "12": 0.25.0
            "13": linux-x86_64
adam_eps:
    value: 1e-08
batch_size:
    value: 64
burn_in:
    value: 20
checkpoint_interval:
    value: 50000
config_path:
    value: /home/kajetan/Documents/inzynierka_kod_zrodlowy/fine_tuned/minigrid/conf/config.yaml
demir_beta1:
    value: 0.7
demir_beta2:
    value: 0.3
demir_encoder_type:
    value: idm
device:
    value: cuda
env_id:
    value: BabyAI-KeyCorridorS4R3-v0
epsilon_decay_steps:
    value: 1000000
epsilon_end:
    value: 0.05
epsilon_start:
    value: 1
eval_episodes:
    value: 5
eval_interval:
    value: 20000
gamma:
    value: 0.997
grad_steps:
    value: 1
hidden_dim:
    value: 256
intrinsic_scale:
    value: 0.05
log_interval:
    value: 2000
lr:
    value: 0.0001
max_grad_norm:
    value: 10
mission_max_tokens:
    value: 24
n_step:
    value: 5
num_threads:
    value: 4
prio_alpha:
    value: 0.6
prio_beta_end:
    value: 1
prio_beta_start:
    value: 0.4
prio_eta:
    value: 0.9
replay_capacity_sequences:
    value: 40000
save_dir:
    value: logs_thesis/minigrid
seed:
    value: 100
target_update_interval:
    value: 2000
total_steps:
    value: 10000000
train_every:
    value: 4
unroll_len:
    value: 40
variant:
    value: r2d2_demir
warmup_steps:
    value: 50000
